name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t nitt-mentoring:latest .
        working-directory: .

      - name: Save Docker Image to Tarball
        run: |
          docker save -o nitt-mentoring.tar nitt-mentoring:latest
        working-directory: .
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "release draft"
          draft: true
          files: |
            nitt-mentoring.tar
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
